version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - 5672:5672
      - 15672:15672  # Optional for RabbitMQ management UI access

  worker:
    build: .
    command: celery -A tasks worker -l info
    depends_on:
      - rabbitmq

volumes:
  # Define a volume to share data between containers (optional for statistics)
  # shared_data:/app/data